// FrontWeb/Vue3/5_router/src/pages/News.vue
<template>
    <div>
        <ul :style="{opacity}">
            <li>news001 <input></li>
            <li>news002 <input></li>
            <li>news003 <input></li>
        </ul>
    </div>
</template>

<script>
export default {
    name: 'News',
    data() {
        return {
            opacity: 1,
        }
    },
    activated() {
        console.log('News组件被激活了')
        this.timer = setInterval(() => {
            console.log('@')
            this.opacity -= 0.01
            if (this.opacity <= 0) this.opacity = 1
        }, 16)
    },
    deactivated() {
        console.log('News组件失活了')
        clearInterval(this.timer)
    },
}
</script>

<style></style>

// FrontWeb/React/sgg/2022 加更内容/代码/react-router6_test/src/pages/News.jsx
import React from 'react'
import {useNavigationType,useResolvedPath} from 'react-router-dom'

export default function News() {
	console.log(useNavigationType())
	console.log('@@',useResolvedPath('/user?id=001&name=tom#qwe'))
	return (
		<ul>
			<li>news001</li>
			<li>news002</li>
			<li>news003</li>
		</ul>
	)
}
