// FrontWeb/React/03_React脚手架/src/Components/List/List.jsx
import React, { Component } from "react";
import Item from "../Item/Item";
import "./List.css";

export default class index extends Component {
  render() {
    const { todos } = this.props;
    return (
      <ul className="todo-main">
        {todos.map((todo) => {
          return <Item key={todo.id} {...todo} />;
        })}
      </ul>
    );
  }
}

// FrontEnd/FrontWeb/Vue3/Vue2/2_组件化开发/todo_list_06/src/components/List.vue
<template>
    <ul class="todo-main">
        <Item v-for="todoObj in todos" :key="todoObj.id" :todo="todoObj"></Item>
    </ul>
</template>

<script>
import Item from './Item.vue';
export default {
    name: 'List',
    components: { Item },
    props: ['todos'],
}

</script>

<style scoped>
/*main*/
.todo-main {
    margin-left: 0px;
    border: 1px solid #ddd;
    border-radius: 2px;
    padding: 0px;
}

.todo-empty {
    height: 40px;
    line-height: 40px;
    border: 1px solid #ddd;
    border-radius: 2px;
    padding-left: 5px;
    margin-top: 10px;
}
</style>
