// FrontEnd/FrontWeb/React/10_router6/05_state/pages/Home.jsx
import React from "react";
import { NavLink, Outlet } from "react-router-dom";

export default function Home() {
  return (
    <div>
      <h1>Home内容</h1>
      <div>
        <ul className="nav nav-tabs">
          <li>
            <NavLink className="list-group-item" to="news">
              News
            </NavLink>
          </li>
          <li>
            <NavLink className="list-group-item" to="message">
              Message
            </NavLink>
          </li>
        </ul>
        {/* 指定子路由规则 */}
        <Outlet />
      </div>
    </div>
  );
}

// FrontWeb/Vue3/5_router/2_params参数/pages/Home.vue
<template>
    <div>
        <h2>Home组件内容</h2>
        <div>
            <ul class="nav nav-tabs">
                <li>
                    <router-link class="list-group-item" active-class="active" :to="{name: 'myNews'}">News</router-link>
                </li>
                <li>
                     <router-link class="list-group-item" active-class="active" :to="{name: 'myMessage'}">Message</router-link>
                </li>
            </ul>
            <div>
                <router-view></router-view>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'Home',
}
</script>

<style></style>
