// FrontWeb/React/sgg/2022 加更内容/代码/react-router6_test/11_src_useInRouterContext/pages/Home.jsx
import React from 'react'
import {NavLink,Outlet} from 'react-router-dom'

export default function Home() {
	return (
		<div>
			<h2>Home组件内容</h2>
			<div>
				<ul className="nav nav-tabs">
					<li>
						<NavLink className="list-group-item" to="news">News</NavLink>
					</li>
					<li>
						<NavLink className="list-group-item" to="message">Message</NavLink>
					</li>
				</ul>
				{/* 指定路由组件呈现的位置 */}
				<Outlet />
			</div>
		</div>
	)
}

// FrontWeb/Vue3/5_router/src/pages/Home.vue
<template>
    <div>
        <h2>Home组件内容</h2>
        <div>
            <ul class="nav nav-tabs">
                <li>
                    <router-link class="list-group-item" active-class="active" :to="{name: 'myNews'}">News</router-link>
                </li>
                <li>
                     <router-link class="list-group-item" active-class="active" :to="{name: 'myMessage'}">Message</router-link>
                </li>
            </ul>
            <div>
                <keep-alive include="News">
                    <router-view></router-view>
                </keep-alive>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'Home',
}
</script>

<style></style>
