// FrontWeb/Vue3/Vue2/5_router/2_params参数/pages/Message.vue
<template>
    <div>
        <ul>
            <li v-for="m in messageList" :key="m.id">
                <!-- 路由跳转并携带query参数, to的字符串写法 -->
                <!-- <router-link :to="`/myDetail?id=${m.id}&title=${m.title}`">{{ m.title }}</router-link> -->


                <router-link :to="`/home/message/detail/${m.id}/${m.title}`">{{ m.title }}</router-link>
                <router-link :to="{
                    name: 'myDetail',
                    params: {
                        id: m.id,
                        title: m.title
                    }
                }">{{ m.title }}</router-link>
                <!-- 路由跳转并携带query参数, to的对象写法 -->
                <!-- <router-link :to="{
                    path: 'myDetail',
                    query: {
                        id: m.id,
                        title: m.title
                    }
                }">{{ m.title }}</router-link> -->
            </li>
        </ul>
        <hr>
        <router-view></router-view>
    </div>
</template>

<script>
export default {
    name: 'Message',
    data() {
        return {
            messageList: [
                { id: 1, title: 'message001' },
                { id: 2, title: 'message002' },
                { id: 3, title: 'message003' },
            ]
        }
    },
    mounted() {
        console.log('this.$route', this.$route);
    }

}
</script>

<style></style>

// FrontEnd/Framework/React/05_react_router/09_query传参/pages/Home/message/Message.jsx
import React, { Component } from "react";
import { Link, Route } from "react-router-dom";
import Detail from "./Detail/Detail";

export default class Message extends Component {
  state = {
    message: [
      { id: "001", title: "message001" },
      { id: "002", title: "message002" },
      { id: "003", title: "message003" },
    ],
  };
  render() {
    const { message } = this.state;
    return (
      <div>
        <ul>
          {message.map((m) => {
            return (
              <li key={m.id}>
                {/* <Link to={`/home/message/detail/${m.id}/${m.title}`}> */}
                <Link to={`/home/message/detail/?id=${m.id}&title=${m.title}`}>
                  {m.title}
                </Link>
              </li>
            );
          })}
        </ul>
        <hr />
        {/* <Route path="/home/message/detail/:id/:title" component={Detail} /> */}
        <Route path="/home/message/detail" component={Detail} />
      </div>
    );
  }
}
