// FrontWeb/React/04_react_ajax/src/components/Search/index.jsx
import React, { Component } from "react";
import axios from "axios";

export default class Search extends Component {
  search = () => {
    const {
      keyWordNode: { value: keyword },
    } = this;
    this.props.updateAppState({
      isFirst: false,
      isLoading: true,
      isError: false,
    });
    axios
      .get(`https://api.github.com/search/users?q=${keyword}`)
      .then((res) => {
        const users = res.data.items.map((item) => {
          return {
            id: item.id,
            login: item.login,
            avatar_url: item.avatar_url,
            html_url: item.html_url,
          };
        });
        this.props.updateAppState({ isLoading: false, users, isError: false });
      })
      .catch((error) => {
        this.props.updateAppState({
          isLoading: false,
          users: [],
          isError: true,
          err: error.message,
        });
        console.log(error);
      });
  };

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">搜索GitHub用户</h3>
        <div>
          <input
            ref={(c) => (this.keyWordNode = c)}
            type="text"
            placeholder="搜索关键词进行搜索"
          />
          &nbsp;<button onClick={this.search}>搜索</button>
        </div>
      </section>
    );
  }
}

// FrontEnd/Framework/Vue3/Vue2/3_Ajax/03_github_proj/src/components/Search.vue
<template>
    <section class="jumbotron">
        <h3 class="jumbotron-heading">Search Github Users</h3>
        <div>
            <input ref="keyType" type="text" placeholder="enter the name you search" v-model="keyWord"
                @keyup.enter="enterSearchUsers" @blur="searchUsers" />&nbsp;
            <button @click="searchUsers">Search</button>
        </div>
    </section>
</template>

<script>
import axios from 'axios'
export default {
    name: 'Search',
    data() {
        return {
            keyWord: '',
        }
    },
    methods: {
        searchUsers() {
            this.$bus.$emit('updateListData', { isFirst: false, isLoading: true, errMsg: '', users: [] })
            axios.get(`https://api.github.com/search/users?q=${this.keyWord}`).then(
                response => {
                    this.$bus.$emit('updateListData', { isLoading: false, errMsg: '', users: response.data.items })
                },
                error => {
                    this.$bus.$emit('updateListData', { isLoading: false, errMsg: error.message, users: [] })
                }
            )
        },
        enterSearchUsers() {
            this.$refs.keyType.blur()
        }
    },
}
</script>

<style scoped></style>
